### ISSUE TITLE
ERROR 500 ACCESS 

### ISSUE THREAD

**Issue by FarmAgri** [google/ChromeBrowserEnterprise#2]
Comunication error:
**500. That’s an error. The server encountered an error and could not complete your request.**
**Failed to load resource: the server responded with a status of 500 ()**

Note that it appears when you want to access the google profile, search functionality.

**Comment by nsamarakkody** [comment]
its likely due to a misconfig - drop me an email and lets look at what you got

**Comment by nsamarakkody** [comment]
closing due to no response
