### ISSUE TITLE
Please add a shortcut key to open a new tab in the same group in the chrome browser.

### ISSUE THREAD

**Issue by huzaifaasim017** [google/ChromeBrowserEnterprise#21]
# New Feature Require
---
I don't know where to contact exactly for the Chrome browser suggestion, but it should be a shortcut key to open a new tab in the same group, like currently if I press (Ctrl + T) this will open a new tab, but many times I want to open the tab in the same group so for that I need to first press (Ctrl + T) and then move that tab into the group.

## Example Video

https://github.com/google/ChromeBrowserEnterprise/assets/64212910/d16ef66b-e538-48d0-9e18-a655431a16a7

**Comment by nsamarakkody** [comment]
You can open a FR directly https://g-issues.chromium.org/issues/new?component=1456152&template=1922672
