### ISSUE TITLE
Could not create object

### ISSUE THREAD

**Issue by vijayan153** [google/ChromeBrowserEnterprise#23]
Chrome upgrade not successful and it throws below error 

![image](https://github.com/google/ChromeBrowserEnterprise/assets/20811816/eee3f76c-3a3e-406d-a3a2-9de1b3d5ea2b)

**Comment by nsamarakkody** [comment]
Can you please report this issue through Chromium bug tracker https://g-issues.chromium.org/u/0/issues/new?component=1456152&template=1923217&pli=1 ? Include the updater log file, command line, and output
